version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: latest
  build:
    commands:
      - echo "Building the app..."
      - npm install
      - npm run build
  post_build:
    commands:
      - echo "Build completed."
      - aws s3 sync ./dist s3://your-bucket-name
artifacts:
  files:
    - '**/*'
